<?php

namespace ContainerFx3gPls;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeMainFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Factory\AttributeMainFactory' shared autowired service.
     *
     * @return \App\Factory\AttributeMainFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/ModelFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/AttributeMainFactory.php';

        return $container->privates['App\\Factory\\AttributeMainFactory'] = new \App\Factory\AttributeMainFactory();
    }
}
