<?php

namespace Container712xyCS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendHistoryOrderProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\SendHistoryOrderProcessor' shared autowired service.
     *
     * @return \App\State\SendHistoryOrderProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/SendHistoryOrderProcessor.php';

        return $container->privates['App\\State\\SendHistoryOrderProcessor'] = new \App\State\SendHistoryOrderProcessor();
    }
}
