<?php

namespace ContainerIfCPoox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartessetProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\CartessetProvider' shared autowired service.
     *
     * @return \App\State\CartessetProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/State/CartessetProvider.php';

        return $container->privates['App\\State\\CartessetProvider'] = new \App\State\CartessetProvider(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
