<?php

namespace ContainerIfCPoox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendOrderProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\SendOrderProcessor' shared autowired service.
     *
     * @return \App\State\SendOrderProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/SendOrderProcessor.php';

        return $container->privates['App\\State\\SendOrderProcessor'] = new \App\State\SendOrderProcessor(($container->privates['App\\Repository\\HistoryRepository'] ?? $container->load('getHistoryRepositoryService')), ($container->privates['App\\Repository\\HistoryDetailedRepository'] ?? $container->load('getHistoryDetailedRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
