<?php

namespace Container3twbFMX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnotatedAppEntityProductApiPlatformElasticsearchFilterTermFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'annotated_app_entity_product_api_platform_elasticsearch_filter_term_filter' shared autowired service.
     *
     * @return \ApiPlatform\Elasticsearch\Filter\TermFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Metadata/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Api/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Filter/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Util/FieldDatatypeTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Filter/AbstractFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Filter/ConstantScoreFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Filter/AbstractSearchFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Filter/TermFilter.php';

        $a = ($container->privates['api_platform.symfony.iri_converter'] ?? self::getApiPlatform_Symfony_IriConverterService($container));

        if (isset($container->privates['annotated_app_entity_product_api_platform_elasticsearch_filter_term_filter'])) {
            return $container->privates['annotated_app_entity_product_api_platform_elasticsearch_filter_term_filter'];
        }

        return $container->privates['annotated_app_entity_product_api_platform_elasticsearch_filter_term_filter'] = new \ApiPlatform\Elasticsearch\Filter\TermFilter(($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService($container)), ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? self::getApiPlatform_Metadata_Property_MetadataFactory_CachedService($container)), ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)), $a, ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), NULL, ['SubAttributes.id' => NULL]);
    }
}
