<?php

namespace ContainerOWWHxDM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronImageUploaderCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CronImageUploaderCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CronImageUploaderCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('CronImageUploader', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\CronImageUploaderCommand')] fn (): \App\Command\CronImageUploaderCommand => ($container->privates['App\\Command\\CronImageUploaderCommand'] ?? $container->load('getCronImageUploaderCommandService')));
    }
}
