<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'SubUser' => [parent::class, 'SubUser', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'extId' => [parent::class, 'extId', null],
        "\0".parent::class."\0".'histories' => [parent::class, 'histories', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isBlocked' => [parent::class, 'isBlocked', null],
        "\0".parent::class."\0".'isRegistered' => [parent::class, 'isRegistered', null],
        "\0".parent::class."\0".'migvans' => [parent::class, 'migvans', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'priceList' => [parent::class, 'priceList', null],
        "\0".parent::class."\0".'recovery' => [parent::class, 'recovery', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'SubUser' => [parent::class, 'SubUser', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'email' => [parent::class, 'email', null],
        'extId' => [parent::class, 'extId', null],
        'histories' => [parent::class, 'histories', null],
        'id' => [parent::class, 'id', null],
        'isBlocked' => [parent::class, 'isBlocked', null],
        'isRegistered' => [parent::class, 'isRegistered', null],
        'migvans' => [parent::class, 'migvans', null],
        'name' => [parent::class, 'name', null],
        'password' => [parent::class, 'password', null],
        'phone' => [parent::class, 'phone', null],
        'priceList' => [parent::class, 'priceList', null],
        'recovery' => [parent::class, 'recovery', null],
        'roles' => [parent::class, 'roles', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
