<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class History extends \App\Entity\History implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'deliveryDate' => [parent::class, 'deliveryDate', null],
        "\0".parent::class."\0".'deliveryPrice' => [parent::class, 'deliveryPrice', null],
        "\0".parent::class."\0".'discount' => [parent::class, 'discount', null],
        "\0".parent::class."\0".'documentType' => [parent::class, 'documentType', null],
        "\0".parent::class."\0".'historyDetaileds' => [parent::class, 'historyDetaileds', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isAgent' => [parent::class, 'isAgent', null],
        "\0".parent::class."\0".'orderComment' => [parent::class, 'orderComment', null],
        "\0".parent::class."\0".'orderExtId' => [parent::class, 'orderExtId', null],
        "\0".parent::class."\0".'orderStatus' => [parent::class, 'orderStatus', null],
        "\0".parent::class."\0".'total' => [parent::class, 'total', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'deliveryDate' => [parent::class, 'deliveryDate', null],
        'deliveryPrice' => [parent::class, 'deliveryPrice', null],
        'discount' => [parent::class, 'discount', null],
        'documentType' => [parent::class, 'documentType', null],
        'historyDetaileds' => [parent::class, 'historyDetaileds', null],
        'id' => [parent::class, 'id', null],
        'isAgent' => [parent::class, 'isAgent', null],
        'orderComment' => [parent::class, 'orderComment', null],
        'orderExtId' => [parent::class, 'orderExtId', null],
        'orderStatus' => [parent::class, 'orderStatus', null],
        'total' => [parent::class, 'total', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
