<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AttributeMain extends \App\Entity\AttributeMain implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'SubAttributes' => [parent::class, 'SubAttributes', null],
        "\0".parent::class."\0".'extId' => [parent::class, 'extId', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isInFilter' => [parent::class, 'isInFilter', null],
        "\0".parent::class."\0".'isInProductCard' => [parent::class, 'isInProductCard', null],
        "\0".parent::class."\0".'isPublished' => [parent::class, 'isPublished', null],
        "\0".parent::class."\0".'orden' => [parent::class, 'orden', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        'SubAttributes' => [parent::class, 'SubAttributes', null],
        'extId' => [parent::class, 'extId', null],
        'id' => [parent::class, 'id', null],
        'isInFilter' => [parent::class, 'isInFilter', null],
        'isInProductCard' => [parent::class, 'isInProductCard', null],
        'isPublished' => [parent::class, 'isPublished', null],
        'orden' => [parent::class, 'orden', null],
        'title' => [parent::class, 'title', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
