<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'SubAttributes' => [parent::class, 'SubAttributes', null],
        "\0".parent::class."\0".'barcode' => [parent::class, 'barcode', null],
        "\0".parent::class."\0".'basePrice' => [parent::class, 'basePrice', null],
        "\0".parent::class."\0".'categoryLvl1' => [parent::class, 'categoryLvl1', null],
        "\0".parent::class."\0".'categoryLvl2' => [parent::class, 'categoryLvl2', null],
        "\0".parent::class."\0".'categoryLvl3' => [parent::class, 'categoryLvl3', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'defaultImagePath' => [parent::class, 'defaultImagePath', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'discount' => [parent::class, 'discount', null],
        "\0".parent::class."\0".'finalPrice' => [parent::class, 'finalPrice', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imagePath' => [parent::class, 'imagePath', null],
        "\0".parent::class."\0".'isPublished' => [parent::class, 'isPublished', null],
        "\0".parent::class."\0".'migvans' => [parent::class, 'migvans', null],
        "\0".parent::class."\0".'orden' => [parent::class, 'orden', null],
        "\0".parent::class."\0".'packQuantity' => [parent::class, 'packQuantity', null],
        "\0".parent::class."\0".'priceListDetaileds' => [parent::class, 'priceListDetaileds', null],
        "\0".parent::class."\0".'sku' => [parent::class, 'sku', null],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null],
        "\0".parent::class."\0".'subProducts' => [parent::class, 'subProducts', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'SubAttributes' => [parent::class, 'SubAttributes', null],
        'barcode' => [parent::class, 'barcode', null],
        'basePrice' => [parent::class, 'basePrice', null],
        'categoryLvl1' => [parent::class, 'categoryLvl1', null],
        'categoryLvl2' => [parent::class, 'categoryLvl2', null],
        'categoryLvl3' => [parent::class, 'categoryLvl3', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'defaultImagePath' => [parent::class, 'defaultImagePath', null],
        'description' => [parent::class, 'description', null],
        'discount' => [parent::class, 'discount', null],
        'finalPrice' => [parent::class, 'finalPrice', null],
        'id' => [parent::class, 'id', null],
        'imagePath' => [parent::class, 'imagePath', null],
        'isPublished' => [parent::class, 'isPublished', null],
        'migvans' => [parent::class, 'migvans', null],
        'orden' => [parent::class, 'orden', null],
        'packQuantity' => [parent::class, 'packQuantity', null],
        'priceListDetaileds' => [parent::class, 'priceListDetaileds', null],
        'sku' => [parent::class, 'sku', null],
        'stock' => [parent::class, 'stock', null],
        'subProducts' => [parent::class, 'subProducts', null],
        'title' => [parent::class, 'title', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
