<?php

namespace ContainerB9Pevoc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetProductsByMigvanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GetProductsByMigvan' shared autowired service.
     *
     * @return \App\Controller\GetProductsByMigvan
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/GetProductsByMigvan.php';

        return $container->services['App\\Controller\\GetProductsByMigvan'] = new \App\Controller\GetProductsByMigvan();
    }
}
