<?php

namespace ContainerOcUEVow;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseHistoryProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\PurchaseHistoryProvider' shared autowired service.
     *
     * @return \App\State\PurchaseHistoryProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/State/PurchaseHistoryProvider.php';

        return $container->privates['App\\State\\PurchaseHistoryProvider'] = new \App\State\PurchaseHistoryProvider(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
