<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFx3gPls\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFx3gPls/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFx3gPls.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFx3gPls\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFx3gPls\App_KernelTestDebugContainer([
    'container.build_hash' => 'Fx3gPls',
    'container.build_id' => 'c43572ad',
    'container.build_time' => 1696072771,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFx3gPls');
