<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIfCPoox\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIfCPoox/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIfCPoox.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIfCPoox\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIfCPoox\App_KernelDevDebugContainer([
    'container.build_hash' => 'IfCPoox',
    'container.build_id' => '01f1d332',
    'container.build_time' => 1697921686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIfCPoox');
