<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxcrXLV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxcrXLV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxcrXLV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxcrXLV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFxcrXLV\App_KernelDevDebugContainer([
    'container.build_hash' => 'FxcrXLV',
    'container.build_id' => 'a2fe79d4',
    'container.build_time' => 1698008357,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxcrXLV');
