<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3twbFMX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3twbFMX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3twbFMX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3twbFMX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3twbFMX\App_KernelDevDebugContainer([
    'container.build_hash' => '3twbFMX',
    'container.build_id' => '6b426217',
    'container.build_time' => 1697301751,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3twbFMX');
